# Cargo.toml

[package]
name = "pwr-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0"
coap = "0"
coap-lite = "0"
# log = "0"
parking_lot = "0"
rocket = "0.5.0-rc.1"
rocket_dyn_templates = { version = "0.1.0-rc.1", features = ["handlebars", "tera"] }
# simplelog = "0"
structopt = "0"
tera = "1"

[build-dependencies]
build-data = "0.1"

# EOF
