# Cargo.toml

[package]
name = "pwr-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

actix-web = "3"
chrono = "0"
coap = "0"
coap-lite = "0"
env_logger = "0"
log = "0"
parking_lot = "0"
structopt = "0"
tera = "1"

[build-dependencies]
build-data = "0.1"

[profile.release]
lto = true
opt-level = 3 #default
# opt-level = 'z'  # Optimize for size.

# EOF
