# Cargo.toml

[package]
name = "pwr-server"
version = "0.1.1"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "*"
anyhow = "*"
askama = "*"
chrono = "*"
coap = "*"
coap-lite = "*"
env_logger = "*"
log = "*"
structopt = "*"

[build-dependencies]
build-data = "*"

[profile.release]
lto = true
opt-level = 3 #default
# opt-level = 'z'  # Optimize for size.

# EOF
