# Cargo.toml

[package]
name = "pwr-server"
version = "0.1.4"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.1"
anyhow = "1.0"
askama = "0.11"
chrono = "0.4"
coap = "0.12"
coap-lite = "0.9"
env_logger = "0.9"
log = "0.4"
structopt = "0.3"

[build-dependencies]
build-data = "0.1"

[profile.release]
lto = true
opt-level = 3 #default
# opt-level = 'z'  # Optimize for size.

# EOF
